Running on host: tikgpu01
In directory: /itet-stor/owendu/net_scratch/Paraphrase
Starting on: Tue Mar 7 13:58:37 CET 2023
SLURM_JOB_ID: 606745
Found cached dataset text (/home/owendu/transformers_cache/text/default-cdc8ff16a5f3ca7c/0.0.0/cb1e9bd71a82ad27976be3b12b407850fe2837d80c22c5e03a28949843a8ace2)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 421.67it/s]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
Traceback (most recent call last):
  File "/usr/itetnas04/data-scratch-01/owendu/data/Paraphrase/paraphrase_trunc.py", line 16, in <module>
    completion = openai.ChatCompletion.create(
  File "/itet-stor/owendu/net_scratch/miniconda3/envs/env/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/itet-stor/owendu/net_scratch/miniconda3/envs/env/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/itet-stor/owendu/net_scratch/miniconda3/envs/env/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/itet-stor/owendu/net_scratch/miniconda3/envs/env/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/itet-stor/owendu/net_scratch/miniconda3/envs/env/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}
 500 {'error': {'message': 'Internal server error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Tue, 07 Mar 2023 13:35:04 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '166', 'Connection': 'keep-alive', 'Vary': 'Origin', 'X-Request-Id': '75ae0cec969ca63c8a00594392ed4c52', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'}
srun: error: tikgpu01: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=606745.0
